name: Build and Push Docker Images to ECR

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - 'weather_data_collectors/**'  # Only trigger when changes to weather collectors
    branches:
      - main

permissions:
  contents: read
  id-token: write
  actions: write 

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        collector: ['historical', 'hourly']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: us-east-1
          role-session-name: GitHubActions

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: weather-${{ matrix.collector }}-collector
          IMAGE_TAG: latest
        run: |
          cd weather_data_collectors/${{ matrix.collector }}
          cp ../requirements.txt .
          
          # Build the Docker image
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          
          # Push the Docker image
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          echo "Image pushed to $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
      
      - name: Trigger Apply with Lambda workflow
        if: matrix.collector == 'hourly'  # Only trigger once after both images are pushed
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'apply.yml',
              ref: 'main',
              inputs: {
                action: 'apply-with-lambda'
              }
            }) 