name: CD

on:
  push:
    branches: [main, master]

permissions:
  contents: read
  id-token: write

jobs:
  push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: eu-west-3
          role-session-name: GitHubActions

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ecr-repo-lambda
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd extract_api_data
          
          # Build and tag the image
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest
          
          # Push both tags
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:latest
          
          # Update Lambda function with new image
          aws lambda update-function-code \
            --function-name movie-api-extractor \
            --image-uri $REGISTRY/$REPOSITORY:$IMAGE_TAG \
            --region eu-west-3